app = "rest-api-java"

[build]
image = "heriniavotra/rest-api-java:latest"

[env]
PORT = "8081"

[[services]]
  internal_port = 8081
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
