FROM nginx:alpine

# Copier seulement les fichiers nécessaires pour l'application web
COPY index.html /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY styles.css /usr/share/nginx/html/

EXPOSE 80

