name: Build Java and Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java
        run: javac -d bin src/*.java
      
      - name: Run server in background
        run: |
          java -cp bin src.Main &
          sleep 5
          curl http://localhost:8081/
      
      - name: Build Docker Image
        run: docker build -t rest-api-java .
