name: Deploy Docker Image to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t rest-api-java .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
          docker tag rest-api-java ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
